# 1. Introduction to NumPy


![](images/numpy_logo.svg)

https://numpy.org

# NumPy

Numpy is an important package providing a powerful N-dimensional array object called 

                                            ndarray

that facilitates calculations with vectors and matrices.

We need to import the package first:

In [1]:
import numpy as np

### Basics

In [2]:
# Creating a numpy array
X = np.array([1,2,3])

X

array([1, 2, 3])

In [16]:
# or alternative way
Y = [-1,0.5,2]
Y = np.array(Y)

Y

array([-1. ,  0.5,  2. ])

In [4]:
# Create a matrix
matrix = np.array([[3.0,2.0,6.0],[2.0,4.0,2.5],[3.0,8.0,4.0]])

matrix

array([[3. , 2. , 6. ],
       [2. , 4. , 2.5],
       [3. , 8. , 4. ]])

### Numpy Methods to create arrays


In [5]:
# Create a sequence of numbers in an array
seq = np.arange(0, 10)

seq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# create an array with random floats between 0 and 1
random_floats = np.random.rand(3,3)

# create an array with random ints between 10 and 100
random_ints = np.random.randint(10, 100, (3,3))

random_floats, random_ints

(array([[0.13918217, 0.48690975, 0.13954346],
        [0.13564598, 0.01846675, 0.72418748],
        [0.97271663, 0.07704253, 0.57912119]]),
 array([[46, 26, 12],
        [52, 13, 19],
        [20, 89, 38]]))

In [7]:
# create an array with only zeros 
zeros = np.zeros((2,2))

zeros

array([[0., 0.],
       [0., 0.]])

In [8]:
ones = np.ones((3, 3))

ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Metadata about ndarrays

In [17]:
type(X), type(Y), type(seq), type(matrix), type(random_ints), type(zeros), type(ones)

(numpy.ndarray,
 numpy.ndarray,
 numpy.ndarray,
 numpy.ndarray,
 numpy.ndarray,
 numpy.ndarray,
 numpy.ndarray)

In [12]:
# this is not an ndarray
not_ndarray = [1,2,3,4]
type(not_ndarray)

list

In [18]:
# get the shape information about the ndarray (very important)
X.shape, Y.shape, seq.shape, matrix.shape, random_ints.shape, zeros.shape, ones.shape

((3,), (3,), (10,), (3, 3), (3, 3), (2, 2), (3, 3))

Here are some other attributes:

|Attribute | Meaning |
|----|---|
|ndarray.ndim | the number of axes (dimensions) of the array dimension.| 
|ndarray.size | the total number of elements of the array. This is equal to the product of the elements of shape.|
|ndarray.dtype | an object describing the type of the elements in the array.|


Examples:

In [19]:
# Examples:

matrix.ndim, matrix.size, matrix.dtype

(2, 9, dtype('float64'))