### Requirements

In [2]:
import numpy as np

# for measuring execution time
import time

# 2. NumPy: Indexing and Computations

### Indexing
The indexing is similar to python lists but there're more options. Multidimensional Indexing is supported. That means, if you have more than one dimension, you can but you don't need to put the second dimension's index into it's own brackts. Here's an example: 

In [11]:
# We want to access the seconds element in the first row of the matrix defines above:
matrix = np.random.rand(3,3)

print(matrix[0][1])    # first option
print(matrix[0,1])     # second option using multidimensional indexing.

0.9700767666048176
0.9700767666048176


Slicing

In [13]:
seq = np.arange(0,10)

seq[2:9]

array([2, 3, 4, 5, 6, 7, 8])

You can also leave out the index (use everything)
or use negative indices to specify the last indices (-1: last item, -2: second last item, and so on)

In [14]:
seq[:], seq[:6], seq[6:], seq[6:-1]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5]),
 array([6, 7, 8, 9]),
 array([6, 7, 8]))

In [15]:
matrix[1:3, 1:3]

array([[0.07746156, 0.05025073],
       [0.38222897, 0.13400318]])

Of course you can not only read, but also overwrite the selected values!

In [16]:
matrix

array([[0.34067404, 0.97007677, 0.68313326],
       [0.78646672, 0.07746156, 0.05025073],
       [0.60357902, 0.38222897, 0.13400318]])

In [17]:
matrix[1:3, 1:3] = np.Infinity # This is a marker for "positive infinity", e.g. when there are errors in the data

In [18]:
matrix

array([[0.34067404, 0.97007677, 0.68313326],
       [0.78646672,        inf,        inf],
       [0.60357902,        inf,        inf]])

### Operations
Operations on numpy arrays are performed elementwise. They're very fast and computationally efficient. That is very helpful if you have a lot of data, imagine an array with 1,000,000 entries! Let's look at an example:

In [19]:
# Python lists
small_list = [1]    # with one entry
large_list = 1000000 * small_list    # repeated 1,000,000 time, thus 1,000,000 entries

# to multiply every element in large_list by 5, we have to loop over every element:
new_large_list = []
for x in large_list:
    new_large_list.append(5*x)

# or using a list comprehension
new_large_list = [5*x for x in large_list]

Now: How long does that take??

In [20]:
# we'll measure the time before we start looping over the pyhton list:
t_start = time.time()
# do the looping:
new_large_list = [5*x for x in large_list]
# measure time again:
t_end = time.time()

duration = t_end - t_start

print(duration)

0.052763938903808594


Now using Numpy instead. The operation * is performed **ELEMENTWISE** on numpy arrays, so all we need to do is:

In [21]:
# create large numpy array from large_list:
large_array = np.array(large_list)

# or use the numpy functions that creates however many 1 s as you want:
large_array = np.ones(1000000)

# How long does it take to multiply each element by 5?
t_start = time.time()

new_large_array = 5 * large_array

t_end = time.time()

duration = t_end - t_start

print(duration)

0.002240896224975586


Some more operations:

In [ ]:
X = np.array([1,2,3])
Y = np.array([-1,0.5,2])

A = X+Y     # element-wise addition
M = X*Y    # element-wise multiplication
D = np.dot(X,Y)    # dot product
D = X @ Y # alternative syntax for dot product

A,M,D