### Requirements

For the last tasks we need to import a custom python script which should already be in the same folder as this jupyter notebook file.

In [2]:
import numpy as np

# the file "source.py" should already be in the same folder
import source

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


## Exercises for lecture 1

**Task a)** Create a Numpy Array with the numbers 1 2 3 4 5 by converting a python list to an array 

In [3]:
# your code
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

**Task b)** Create a Numpy Array with the numbers 1 2 3 4 5 by using the numpy arange method

In [4]:
# your code
np.arange(1, 6)

array([1, 2, 3, 4, 5])

**Task c)** Create the following matrix as ndarray object:

$$\begin{pmatrix}
1 & 2 & 3\\
5 & 8 & 13 \\
21 & 34 & 55
\end{pmatrix}$$

In [5]:
# your code
np.array([[1, 2, 3],[5, 8, 13],[21, 34, 55]])

array([[ 1,  2,  3],
       [ 5,  8, 13],
       [21, 34, 55]])

**Task d)** Create a vector with 100 random integers between -50 and 50.

In [6]:
# your code
np.random.randint(-50, 50, 100)

array([-37,  12, -44,  40, -15, -49, -46, -47, -23,  28,  14, -39, -23,
       -14, -14,  24, -43,  22, -47,  -1,  -8, -39, -36,  32, -10,   3,
         3, -15,   8,  -7, -26,  -2,  22, -13, -44,  35, -11,  46, -44,
        41, -30, -19, -36,  26, -47,   1, -49,  48, -50,  -4, -36,   4,
        27, -48, -17, -49, -42, -10,   9, -49, -11, -22, -16,   7,  21,
        36,   8, -25,  26,  10, -46,  46,  49, -33, -26,  47, -41, -43,
       -34, -24,  -6,  41, -22,  35, -45,  46,   9, -40,  46,  36, -31,
       -47,  -3,  -4,  16,  45,   6, -43,   9, -36])

**Task e)** Create a matrix with random values between 0 and 1 and size $17 \times 128$

In [8]:
# your code
matrix = np.random.rand(17, 128)

print(matrix.shape)

(17, 128)
[[0.9805819  0.57634205 0.80673178 ... 0.92966624 0.52913109 0.40077363]
 [0.58898168 0.21793743 0.96059689 ... 0.40787796 0.14276525 0.50703596]
 [0.99349776 0.8536051  0.4427178  ... 0.71973717 0.46225967 0.90581375]
 ...
 [0.39865152 0.26880823 0.46990745 ... 0.56045203 0.48756944 0.7281786 ]
 [0.2634594  0.97630396 0.38173642 ... 0.10085065 0.32714078 0.51216008]
 [0.74324889 0.19390437 0.29173971 ... 0.95595484 0.60100713 0.15486855]]


**Task f)** Create an ndarray with random values between 0 and 1 and size $10 \times 10 \times 150 \times 1$

In [9]:
# your code
ndarray = np.random.rand(10, 10, 150, 1)

print(ndarray.shape)

(10, 10, 150, 1)


**Task g)** Create an ndarray with only zeros and size $4 \times 4 \times 100 \times 100$

In [11]:
# your code
ndarray = np.zeros((4, 4, 100, 100))

print(ndarray.shape)

(4, 4, 100, 100)


**Tasks h) i) j)**
Analyse the given ndarrays regarding the shape, amount of data and data type. 

In [25]:
# h)
array_1g =  source.get_hidden_array_1()


# your code

In [26]:
# i)
array_1h =  source.get_hidden_array_2()

# your code

In [25]:
# j)
array_1j =  source.get_hidden_array_4()

# your code