### Requirements

In [1]:
import numpy as np

# 5. NumPy: Array manipulation

### Shaping

1. **reshaping**: raveling the array (using the given index order), then inserting the elements from the raveled array into the new array using the same kind of index ordering as was used for the raveling.

                                     .reshape(newshape)
                               
2. **flatten**: collapsing an array into one dimension:

                                       .flatten()
                                    

Reshaping an array with 1 dimension into an array with 2 dimensions:

In [2]:
numbers = np.arange(0,10)
numbers_rs = numbers.reshape((2,5))

print(numbers)
print(numbers_rs)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


Reshaping an array with 2 dimensions into an array with 2 dimensions:

In [5]:
matrix = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
matrix_rs = matrix.reshape((4,3))

print(matrix)
print(matrix_rs)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Using reshaping with -1 if you do not want to specify amount of items


In [4]:
matrix = np.zeros((100,40,13,9))

matrix2 = matrix.reshape((100, -1))

matrix.shape, matrix2.shape

((100, 40, 13, 9), (100, 4680))

Flatten an array:

In [5]:
matrix = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
matrix_flat = matrix.flatten()

print(matrix)
print(matrix_flat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Stacking
You can stack together different arrays along a given axis.
Here are three possibile ways to do this:

In [6]:
ones = np.array([[1,1,1,1],[1,1,1,1]])
zeros = np.array([[0,0,0,0],[0,0,0,0]])

ones, zeros

(array([[1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0]]))

#### vstack
Takes a tuple of arrays and stack them vertically

In [7]:
np.vstack((ones, zeros, ones))

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### hstack
Takes a tuple of np arrays and stack them horizontally

In [8]:
np.hstack((ones, zeros, ones))

array([[1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1]])

#### concatenate

vstack and hstack in one function: you can give the axis along which you want to stack a tuple of array.

In [9]:
# 0 means stack the data vertically
axis_v = 0

np.concatenate((ones, zeros, ones), axis=axis_v)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
# and 1 means stack the data horizontally
axis_h = 1

np.concatenate((ones, zeros, ones), axis=axis_h)

array([[1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1]])

One example of deleting one row by collecting all others:

In [11]:
matrix = np.ones((100,8))

# deleting the sixth row
matrix2 = np.vstack((matrix[:5], matrix[6:]))

matrix.shape, matrix2.shape

((100, 8), (99, 8))

...but you can also use the np.delete method

In [12]:
matrix = np.ones((100,8))

# deleting the sixth row
matrix2 = np.delete(matrix, 5, axis=0)

matrix.shape, matrix2.shape

((100, 8), (99, 8))

### Finding unique elements

In [13]:
sample = np.array([6,3,6,8,8,3,1,2,4])

np.unique(sample)

array([1, 2, 3, 4, 6, 8])

Can also be used to return the unique rows/ columns of a matrix:

In [14]:
sample2 = np.array([[1,2,1],[4,6,4],[1,2,1]])

# Unique rows
print('Unique rows \n', np.unique(sample2,axis=0))

# Unique columns
print('Unique columns \n', np.unique(sample2,axis=1))

Unique rows 
 [[1 2 1]
 [4 6 4]]
Unique columns 
 [[1 2]
 [4 6]
 [1 2]]
