### Requirements

In [1]:
import numpy as np

# the file "source.py" should already be in the same folder
import source

## Exercises for lecture 2

In general, try to use numpy arrays instead of loops for the solutions.

**Task a)** Create a numpy array with 1000 entries and each entry has the value 10.

In [2]:
np.ones(1000)*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10

**Task b)** Create two numpy vectors with random values between 0 and 1 (length 40) and add them together.

In [3]:
a = np.random.rand(40)
b = np.random.rand(40)

a+b

array([1.2274424 , 1.30333401, 0.55005593, 0.9581071 , 0.97097479,
       0.80604903, 1.1944322 , 1.11647874, 1.05873983, 1.00783873,
       1.16885488, 0.72509395, 1.3030418 , 0.89899832, 1.14972018,
       0.81215061, 1.4437547 , 1.0865351 , 1.30599848, 0.97906523,
       1.31928554, 1.03731121, 1.46205172, 1.24898359, 1.10919448,
       0.9758774 , 1.20357552, 0.24575705, 0.75376405, 1.08206174,
       0.68998266, 0.64197159, 1.46435151, 1.57606876, 1.57594067,
       0.78416905, 1.27131227, 0.17741276, 0.4383418 , 0.87984821])

**Task c)** Print out the third row vector and the seventh column vector of the given matrix *mat* and add them together.

In [4]:
mat = source.get_hidden_array_5()

row_3 = mat[2]
column_7 = mat[:, 6]

row_3 + column_7

array([0.66993651, 0.4437361 , 0.49181843, 0.67097561, 0.76778106,
       0.87366846, 0.34059801, 1.28550479, 1.32202075, 0.56918324])

**Task d)** Implement the following dot product:
$$ 
    \pmatrix{4 & 3 & 1 & 1} \cdot \pmatrix{1 & -5 & 2 & 19 \\ -2 & 1 & -3 & -25  \\ 2 & 15 & 2 & -2  \\ 1 & 3 & 0 & 2 } = 
$$

In [5]:
vector = np.array([4,3,1,1])
mat = np.array([[1,-5,2,19],[-2,1,-3, -25], [2,15,2,-2], [1,3,0,2]])

vector @ mat

array([1, 1, 1, 1])

**Task e)** Implement the following dot product:
$$ 
    \pmatrix{17 & 18 & 19 & 20 & 21 & 22 & 23 & 24 & 25 } \cdot \pmatrix{-47 \\ -46 \\ -45 \\ -44 \\ -43 \\ -42 \\ -41 \\ -40 \\ -39 } = 
$$

In [6]:
a = np.arange(17,26)
b = np.arange(-47, -38)

a @ b

-8067