### Requirements

For the last tasks we need to import a custom python script which should already be in the same folder as this jupyter notebook file.

In [1]:
import numpy as np

# the file "source.py" should already be in the same folder
import source

## Exercises for lecture 1

**Task a)** Create a Numpy Array with the numbers 1 2 3 4 5 by converting a python list to an array 

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

**Task b)** Create a Numpy Array with the numbers 1 2 3 4 5 by using the numpy arange method

In [3]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

**Task c)** Create the following matrix as ndarray object:

$$\begin{pmatrix}
1 & 2 & 3\\
5 & 8 & 13 \\
21 & 34 & 55
\end{pmatrix}$$

In [4]:
np.array([[1,2,3], [5,8,13], [21,34,55]])

array([[ 1,  2,  3],
       [ 5,  8, 13],
       [21, 34, 55]])

**Task d)** Create a vector with 100 random integers between -50 and 50.

In [5]:
np.random.randint(-50,50, 100)

array([-24,  20,  34, -40, -22,  32, -28,  39,  18,  37, -48,  -3, -28,
       -16, -42, -25,  10,  -5,  40, -37, -33,  19,  24,  35,  33, -29,
       -22, -49,  -9,   5, -44,   1,  44, -26,  35,   6,  25,   2,  -9,
        -4,   8,  18,  10,  23, -45, -22,  46,  -7,  49,   3, -29, -50,
       -45,  -5,  46, -13,  34,  11,   3,  47, -44, -10,  16, -45,  35,
        -3,  49, -22,   4, -38,  -3, -36,  48,   5,  47,   0,  12,  45,
        25,   1,  37, -17, -39, -44,  22,   7,  39, -23,  -7,  -4,  36,
       -46,  40,  45,  -8, -29,  47,  11, -13, -49])

**Task e)** Create a matrix with random values between 0 and 1 and size $17 \times 128$

In [6]:
mat = np.random.rand(17,128)

print(mat.shape)
print(mat)

(17, 128)
[[0.69350544 0.69932028 0.65243072 ... 0.7151458  0.29200815 0.7453795 ]
 [0.70936341 0.81767464 0.19603055 ... 0.88387856 0.05222623 0.41567073]
 [0.77549848 0.57052042 0.63673278 ... 0.42559544 0.07246974 0.2762098 ]
 ...
 [0.01941066 0.16164422 0.47777861 ... 0.93569577 0.78219925 0.50869385]
 [0.63013717 0.41469054 0.60502014 ... 0.93221604 0.68465311 0.80441218]
 [0.32034613 0.60696602 0.41741921 ... 0.76371115 0.28148167 0.90523341]]


**Task f)** Create an ndarray with random values between 0 and 1 and size $10 \times 10 \times 150 \times 1$

In [7]:
ndarray = np.random.rand(10,10,150,1)

print(type(ndarray))
print(ndarray.shape)
print(ndarray)

<class 'numpy.ndarray'>
(10, 10, 150, 1)
[[[[0.44289638]
   [0.39415733]
   [0.19220221]
   ...
   [0.07217142]
   [0.03273985]
   [0.60999579]]

  [[0.60596651]
   [0.1880556 ]
   [0.58646585]
   ...
   [0.20969207]
   [0.00550232]
   [0.77264095]]

  [[0.71881955]
   [0.11511562]
   [0.71260028]
   ...
   [0.37341078]
   [0.06150636]
   [0.97648345]]

  ...

  [[0.67857879]
   [0.85836424]
   [0.24829242]
   ...
   [0.11554869]
   [0.73204007]
   [0.06963755]]

  [[0.93223387]
   [0.36266028]
   [0.94837462]
   ...
   [0.66808798]
   [0.72115145]
   [0.15477052]]

  [[0.41462944]
   [0.68970371]
   [0.04633389]
   ...
   [0.34302939]
   [0.92496072]
   [0.67284129]]]


 [[[0.33097528]
   [0.36454173]
   [0.16209708]
   ...
   [0.67722368]
   [0.28498251]
   [0.48109982]]

  [[0.86999977]
   [0.85968779]
   [0.52295202]
   ...
   [0.73918496]
   [0.44176991]
   [0.10389177]]

  [[0.95451901]
   [0.26336181]
   [0.45894126]
   ...
   [0.2698905 ]
   [0.05334532]
   [0.2697086 ]]

  ...

**Task g)** Create an ndarray with only zeros and size $4 \times 4 \times 100 \times 100$

In [8]:
ndarray = np.zeros((4,4,100,100))

print(type(ndarray))
print(ndarray.shape)
print(ndarray)

<class 'numpy.ndarray'>
(4, 4, 100, 100)
[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. .

**Tasks h) i) j)**
Analyse the given ndarrays regarding the shape, amount of data and data type. 

In [9]:
# h)
array_1g =  source.get_hidden_array_1()


print(array_1g.shape)
print(array_1g.size)
print(array_1g.dtype)
print(array_1g)

(20, 170, 2000)
6800000
int16
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [10]:
# i)
array_1h =  source.get_hidden_array_2()

print(array_1h.shape)
print(array_1h.size)
print(array_1h.dtype)
print(array_1h)

(1, 1, 1, 1, 5000, 10)
50000
float64
[[[[[[0. 0. 0. ... 0. 0. 0.]
     [0. 0. 0. ... 0. 0. 0.]
     [0. 0. 0. ... 0. 0. 0.]
     ...
     [0. 0. 0. ... 0. 0. 0.]
     [0. 0. 0. ... 0. 0. 0.]
     [0. 0. 0. ... 0. 0. 0.]]]]]]


In [11]:
# j)
array_1j =  source.get_hidden_array_4()

print(array_1j.shape)
print(array_1j.size)
print(array_1j.dtype)
print(array_1j)

(5, 2)
10
<U2
[['ab' 'bb']
 ['cb' 'db']
 ['eb' 'fb']
 ['gb' 'hb']
 ['ib' 'jb']]


All three ndarrays have completly different shapes and data types. The first two have only zeros, but first they are encoded as int16 (Integer value with 16 bits reserved: values are in range -32768 to 32767) and then as float64 (Double precision floating point). 

The last ndarray consists of pairs of two characters. 